// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UploadServer.Data;

#nullable disable

namespace UploadServer.Migrations
{
    [DbContext(typeof(VideoDbContext))]
    [Migration("20260520120000_RefactorUserAuth")]
    partial class RefactorUserAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UploadServer.Models.AiCoachAnalysis", b =>
                {
                    b.Property<string>("Id").HasMaxLength(36).HasColumnType("varchar(36)").HasColumnName("id");
                    b.Property<string>("ClipB2Path").HasMaxLength(512).HasColumnType("varchar(512)").HasColumnName("clip_b2_path");
                    b.Property<DateTime?>("CompletedAt").HasColumnType("datetime").HasColumnName("completed_at");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime").HasColumnName("created_at");
                    b.Property<string>("ErrorTypeHint").HasMaxLength(64).HasColumnType("varchar(64)").HasColumnName("error_type_hint");
                    b.Property<string>("ResultJson").HasColumnType("LONGTEXT").HasColumnName("result_json");
                    b.Property<int>("RetryCount").ValueGeneratedOnAdd().HasColumnType("int").HasDefaultValue(0).HasColumnName("retry_count");
                    b.Property<string>("Severity").HasMaxLength(16).HasColumnType("varchar(16)").HasColumnName("severity");
                    b.Property<string>("Status").IsRequired().ValueGeneratedOnAdd().HasMaxLength(50).HasColumnType("varchar(50)").HasDefaultValue("pending").HasColumnName("status");
                    b.Property<string>("Summary").HasColumnType("TEXT").HasColumnName("summary");
                    b.Property<string>("VideoId").IsRequired().HasMaxLength(36).HasColumnType("varchar(36)").HasColumnName("video_id");
                    b.HasKey("Id");
                    b.HasIndex("Status").HasDatabaseName("idx_ai_coach_status");
                    b.HasIndex("VideoId").HasDatabaseName("idx_ai_coach_video_id");
                    b.ToTable("ai_coach_analyses", (string)null);
                });

            modelBuilder.Entity("UploadServer.Models.File", b =>
                {
                    b.Property<string>("Id").HasMaxLength(36).HasColumnType("varchar(36)").HasColumnName("id");
                    b.Property<DateTime?>("CompletedAt").HasColumnType("datetime").HasColumnName("completed_at");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime").HasColumnName("created_at");
                    b.Property<string>("ErrorMessage").HasColumnType("TEXT").HasColumnName("error_message");
                    b.Property<string>("FileName").IsRequired().HasMaxLength(255).HasColumnType("varchar(255)").HasColumnName("file_name");
                    b.Property<string>("FilePath").IsRequired().HasMaxLength(500).HasColumnType("varchar(500)").HasColumnName("file_path");
                    b.Property<long>("FileSize").ValueGeneratedOnAdd().HasColumnType("bigint").HasDefaultValue(0L).HasColumnName("file_size");
                    b.Property<string>("MimeType").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)").HasColumnName("mime_type");
                    b.Property<string>("SourceLocalFilePath").HasColumnType("longtext");
                    b.Property<string>("Status").IsRequired().ValueGeneratedOnAdd().HasMaxLength(50).HasColumnType("varchar(50)").HasDefaultValue("pending").HasColumnName("status");
                    b.Property<string>("Type").IsRequired().HasMaxLength(50).HasColumnType("varchar(50)").HasColumnName("type");
                    b.Property<string>("VideoId").IsRequired().HasMaxLength(36).HasColumnType("varchar(36)").HasColumnName("video_id");
                    b.HasKey("Id");
                    b.HasIndex("Status").HasDatabaseName("idx_file_status");
                    b.HasIndex("Type").HasDatabaseName("idx_file_type");
                    b.HasIndex("VideoId").HasDatabaseName("idx_file_video_id");
                    b.HasIndex("VideoId", "Type").HasDatabaseName("idx_file_video_type");
                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("UploadServer.Models.ProcessQueueItem", b =>
                {
                    b.Property<string>("Id").HasMaxLength(36).HasColumnType("varchar(36)").HasColumnName("id");
                    b.Property<DateTime?>("CompletedAt").HasColumnType("datetime").HasColumnName("completed_at");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime").HasColumnName("created_at");
                    b.Property<bool>("IsSuccess").ValueGeneratedOnAdd().HasColumnType("tinyint(1)").HasDefaultValue(false).HasColumnName("is_success");
                    b.Property<int>("RetryCount").ValueGeneratedOnAdd().HasColumnType("int").HasDefaultValue(0).HasColumnName("retry_count");
                    b.Property<DateTime?>("StartedAt").HasColumnType("datetime").HasColumnName("started_at");
                    b.Property<string>("Status").IsRequired().ValueGeneratedOnAdd().HasMaxLength(50).HasColumnType("varchar(50)").HasDefaultValue("queued").HasColumnName("status");
                    b.Property<string>("VideoId").IsRequired().HasMaxLength(36).HasColumnType("varchar(36)").HasColumnName("video_id");
                    b.HasKey("Id");
                    b.HasIndex("IsSuccess").HasDatabaseName("idx_queue_is_success");
                    b.HasIndex("Status").HasDatabaseName("idx_queue_status");
                    b.HasIndex("VideoId").HasDatabaseName("idx_queue_video_id");
                    b.HasIndex("CompletedAt", "Status").HasDatabaseName("idx_queue_completed_status");
                    b.HasIndex("Status", "CreatedAt").HasDatabaseName("idx_queue_status_created");
                    b.ToTable("process_queue", (string)null);
                });

            modelBuilder.Entity("UploadServer.Models.ShareLink", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int").HasColumnName("id");
                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("B2FileName").IsRequired().HasMaxLength(255).HasColumnType("varchar(255)").HasColumnName("b2_file_name");
                    b.Property<bool>("Confirmed").ValueGeneratedOnAdd().HasColumnType("tinyint(1)").HasDefaultValue(false).HasColumnName("confirmed");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime").HasColumnName("created_at");
                    b.Property<int>("DownloadCount").ValueGeneratedOnAdd().HasColumnType("int").HasDefaultValue(0).HasColumnName("download_count");
                    b.Property<DateTime>("ExpiresAt").HasColumnType("datetime").HasColumnName("expires_at");
                    b.Property<string>("ShareCode").IsRequired().HasMaxLength(16).HasColumnType("varchar(16)").HasColumnName("share_code");
                    b.Property<string>("SharerName").HasMaxLength(100).HasColumnType("varchar(100)").HasColumnName("sharer_name");
                    b.Property<long>("SizeBytes").HasColumnType("bigint").HasColumnName("size_bytes");
                    b.Property<string>("Title").HasMaxLength(255).HasColumnType("varchar(255)").HasColumnName("title");
                    b.HasKey("Id");
                    b.HasIndex("ExpiresAt").HasDatabaseName("idx_share_expires_at");
                    b.HasIndex("ShareCode").IsUnique().HasDatabaseName("idx_share_code");
                    b.ToTable("share_links", (string)null);
                });

            modelBuilder.Entity("UploadServer.Models.User", b =>
                {
                    b.Property<string>("Id").HasMaxLength(36).HasColumnType("varchar(36)").HasColumnName("id");
                    b.Property<DateOnly?>("AdClaimedDate").HasColumnType("date").HasColumnName("ad_claimed_date");
                    b.Property<int>("AdClaimedToday").ValueGeneratedOnAdd().HasColumnType("int").HasDefaultValue(0).HasColumnName("ad_claimed_today");
                    b.Property<string>("AvatarUrl").HasMaxLength(500).HasColumnType("varchar(500)").HasColumnName("avatar_url");
                    b.Property<int>("BonusBalls").ValueGeneratedOnAdd().HasColumnType("int").HasDefaultValue(0).HasColumnName("bonus_balls");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime").HasColumnName("created_at");
                    b.Property<string>("DisplayName").IsRequired().HasMaxLength(255).HasColumnType("varchar(255)").HasColumnName("display_name");
                    b.Property<string>("Email").IsRequired().HasMaxLength(255).HasColumnType("varchar(255)").HasColumnName("email");
                    b.Property<DateOnly?>("FeedbackClaimedDate").HasColumnType("date").HasColumnName("feedback_claimed_date");
                    b.Property<string>("InviteCode").HasMaxLength(16).HasColumnType("varchar(16)").HasColumnName("invite_code");
                    b.Property<int>("InviteCount").ValueGeneratedOnAdd().HasColumnType("int").HasDefaultValue(0).HasColumnName("invite_count");
                    b.Property<string>("InvitedByCode").HasMaxLength(16).HasColumnType("varchar(16)").HasColumnName("invited_by_code");
                    b.Property<DateTime?>("LastLoginAt").HasColumnType("datetime").HasColumnName("last_login_at");
                    b.Property<string>("Plan").IsRequired().ValueGeneratedOnAdd().HasMaxLength(50).HasColumnType("varchar(50)").HasDefaultValue("free").HasColumnName("plan");
                    b.Property<string>("Status").IsRequired().ValueGeneratedOnAdd().HasMaxLength(50).HasColumnType("varchar(50)").HasDefaultValue("active").HasColumnName("status");
                    b.Property<int>("TodayUsed").ValueGeneratedOnAdd().HasColumnType("int").HasDefaultValue(0).HasColumnName("today_used");
                    b.Property<DateOnly?>("TodayUsedDate").HasColumnType("date").HasColumnName("today_used_date");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime").HasColumnName("updated_at");
                    b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("varchar(100)").HasColumnName("username");
                    b.HasKey("Id");
                    b.HasIndex("CreatedAt").HasDatabaseName("idx_user_created_at");
                    b.HasIndex("Email").IsUnique().HasDatabaseName("uk_email");
                    b.HasIndex("InviteCode").IsUnique().HasDatabaseName("uk_invite_code");
                    b.HasIndex("Status").HasDatabaseName("idx_user_status");
                    b.HasIndex("Username").IsUnique().HasDatabaseName("uk_username");
                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("UploadServer.Models.UserAuth", b =>
                {
                    b.Property<string>("Id").HasMaxLength(36).HasColumnType("varchar(36)").HasColumnName("id");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime").HasColumnName("created_at");
                    b.Property<string>("CredentialHash").HasMaxLength(255).HasColumnType("varchar(255)").HasColumnName("credential_hash");
                    b.Property<DateTime?>("LastUsedAt").HasColumnType("datetime").HasColumnName("last_used_at");
                    b.Property<string>("MetadataJson").HasColumnType("TEXT").HasColumnName("metadata_json");
                    b.Property<string>("Provider").IsRequired().HasMaxLength(50).HasColumnType("varchar(50)").HasColumnName("provider");
                    b.Property<string>("ProviderUserId").IsRequired().HasMaxLength(255).HasColumnType("varchar(255)").HasColumnName("provider_user_id");
                    b.Property<string>("UserId").IsRequired().HasMaxLength(36).HasColumnType("varchar(36)").HasColumnName("user_id");
                    b.HasKey("Id");
                    b.HasIndex("UserId").HasDatabaseName("idx_auth_user_id");
                    b.HasIndex("Provider", "ProviderUserId").IsUnique().HasDatabaseName("uk_auth_provider_uid");
                    b.ToTable("user_auths", (string)null);
                });

            modelBuilder.Entity("UploadServer.Models.UserFeedback", b =>
                {
                    b.Property<string>("Id").HasMaxLength(36).HasColumnType("varchar(36)").HasColumnName("id");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime").HasColumnName("created_at");
                    b.Property<string>("Text").IsRequired().HasColumnType("TEXT").HasColumnName("text");
                    b.Property<string>("Type").IsRequired().ValueGeneratedOnAdd().HasMaxLength(20).HasColumnType("varchar(20)").HasDefaultValue("other").HasColumnName("type");
                    b.Property<string>("UserId").IsRequired().HasMaxLength(36).HasColumnType("varchar(36)").HasColumnName("user_id");
                    b.HasKey("Id");
                    b.HasIndex("CreatedAt").HasDatabaseName("idx_feedback_created_at");
                    b.HasIndex("UserId").HasDatabaseName("idx_feedback_user_id");
                    b.ToTable("user_feedbacks", (string)null);
                });

            modelBuilder.Entity("UploadServer.Models.Video", b =>
                {
                    b.Property<string>("Id").HasMaxLength(36).HasColumnType("varchar(36)").HasColumnName("id");
                    b.Property<double?>("AudioCrispness").HasColumnType("DOUBLE").HasColumnName("audio_crispness");
                    b.Property<DateTime?>("CompletedAt").HasColumnType("datetime").HasColumnName("completed_at");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime").HasColumnName("created_at");
                    b.Property<double?>("EndSecond").HasColumnType("DOUBLE").HasColumnName("end_second");
                    b.Property<bool?>("GoodShot").HasColumnType("tinyint(1)").HasColumnName("good_shot");
                    b.Property<double?>("HitSecond").HasColumnType("DOUBLE").HasColumnName("hit_second");
                    b.Property<string>("Name").IsRequired().HasMaxLength(255).HasColumnType("varchar(255)").HasColumnName("name");
                    b.Property<string>("ParentVideoId").HasMaxLength(36).HasColumnType("varchar(36)").HasColumnName("parent_video_id");
                    b.Property<double?>("PeakValue").HasColumnType("DOUBLE").HasColumnName("peak_value");
                    b.Property<double?>("StartSecond").HasColumnType("DOUBLE").HasColumnName("start_second");
                    b.Property<string>("Status").IsRequired().ValueGeneratedOnAdd().HasMaxLength(50).HasColumnType("varchar(50)").HasDefaultValue("pending").HasColumnName("status");
                    b.Property<string>("Type").IsRequired().ValueGeneratedOnAdd().HasMaxLength(50).HasColumnType("varchar(50)").HasDefaultValue("original").HasColumnName("type");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime").HasColumnName("updated_at");
                    b.Property<string>("UserId").IsRequired().HasMaxLength(36).HasColumnType("varchar(36)").HasColumnName("user_id");
                    b.HasKey("Id");
                    b.HasIndex("CreatedAt").HasDatabaseName("idx_video_created_at");
                    b.HasIndex("ParentVideoId").HasDatabaseName("idx_video_parent_id");
                    b.HasIndex("Status").HasDatabaseName("idx_video_status");
                    b.HasIndex("Type").HasDatabaseName("idx_video_type");
                    b.HasIndex("UserId").HasDatabaseName("idx_video_user_id");
                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("UploadServer.Models.AiCoachAnalysis", b =>
                {
                    b.HasOne("UploadServer.Models.Video", "Video").WithMany().HasForeignKey("VideoId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Video");
                });

            modelBuilder.Entity("UploadServer.Models.File", b =>
                {
                    b.HasOne("UploadServer.Models.Video", "Video").WithMany("Files").HasForeignKey("VideoId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Video");
                });

            modelBuilder.Entity("UploadServer.Models.ProcessQueueItem", b =>
                {
                    b.HasOne("UploadServer.Models.Video", "Video").WithMany("QueueItems").HasForeignKey("VideoId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Video");
                });

            modelBuilder.Entity("UploadServer.Models.UserAuth", b =>
                {
                    b.HasOne("UploadServer.Models.User", "User").WithMany("UserAuths").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("UploadServer.Models.UserFeedback", b =>
                {
                    b.HasOne("UploadServer.Models.User", "User").WithMany("Feedbacks").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("UploadServer.Models.Video", b =>
                {
                    b.HasOne("UploadServer.Models.User", "User").WithMany("Videos").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("UploadServer.Models.User", b =>
                {
                    b.Navigation("Feedbacks");
                    b.Navigation("UserAuths");
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("UploadServer.Models.Video", b =>
                {
                    b.Navigation("Files");
                    b.Navigation("QueueItems");
                });
#pragma warning restore 612, 618
        }
    }
}
