name: iOS Flutter 建置與部署

# 當有 push 或 pull_request 觸發時執行 workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      # 取得最新程式碼
      - name: 取得程式碼
        uses: actions/checkout@v4

      # 設定 Flutter 環境
      - name: 設定 Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.35.1'

      # ---------- 建置前準備 ----------
      # 啟用 iOS 支援
      - name: 啟用 iOS 支援
        run: flutter config --enable-ios

      # 安裝缺少的 iOS 平台，避免因 Xcode 未安裝對應版本而建置失敗
      - name: 安裝 iOS 平台
        run: |
          # 接受授權條款，確保後續操作合法
          sudo xcodebuild -license accept
          # 嘗試下載 iOS 平台，若失敗代表模擬器服務未啟動
          sudo xcodebuild -downloadPlatform iOS || (
            # 啟動 Xcode 相關服務後再重試下載
            sudo xcodebuild -runFirstLaunch || true
            sudo xcodebuild -downloadPlatform iOS
          )

      # 判斷專案類型，Plugin 需到 example/ 中操作
      - name: 判斷專案類型
        id: where
        shell: bash
        run: |
          if grep -q '^plugin:' pubspec.yaml; then
            echo "dir=example" >> $GITHUB_OUTPUT
          else
            echo "dir=." >> $GITHUB_OUTPUT
          fi

      # 確保 iOS 平台資料夾存在並更新，避免未設定導致建置失敗
      - name: 確保 iOS 平台資料夾
        working-directory: ${{ steps.where.outputs.dir }}
        run: |
          flutter create --platforms=ios --overwrite .
          ls -la ios || true

      # ---------- 安裝套件 ----------
      - name: 安裝套件
        working-directory: ${{ steps.where.outputs.dir }}
        run: flutter pub get

      # ---------- 程式檢查 ----------
      - name: 程式碼靜態分析
        working-directory: ${{ steps.where.outputs.dir }}
        # 僅檢查應用程式的 lib 目錄，避免分析本地套件造成錯誤
        run: flutter analyze lib

      # ---------- 建置 ----------
      - name: 建置 iOS 執行檔
        working-directory: ${{ steps.where.outputs.dir }}
        # 不進行簽名，只產出可打包的 Runner.app
        run: flutter build ios --release --no-codesign

      # ---------- 產出 ----------
      - name: 打包應用程式
        working-directory: ${{ steps.where.outputs.dir }}
        # 將 Runner.app 打包為 .ipa 供下載
        run: |
          APP=$(find build/ios/iphoneos -maxdepth 1 -name "*.app" -print -quit)
          mkdir Payload
          cp -R "$APP" Payload/
          zip -r app-ios.ipa Payload
          rm -rf Payload

      - name: 上傳建置產物
        uses: actions/upload-artifact@v4
        with:
          name: app-ios
          path: ${{ steps.where.outputs.dir }}/app-ios.ipa
